apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: genai

spec:
  replicas: 1

  selector:
    matchLabels:
      app: backend

  template:
    metadata:
      labels:
        app: backend

    spec:
      containers:
        - name: backend
          image: chatbot-backend:latest
          imagePullPolicy: Never

          ports:
            - containerPort: 8000

          env:
            - name: DATABASE_URL
              value: postgresql://chatbot_user:chatbot_pass@postgres:5432/genai_chatbot

            # ✅ SECURE SECRET (NO HARDCODE)
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: OPENAI_API_KEY

          resources:
            requests:
              cpu: "100m"
            limits:
              cpu: "500m"

---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: genai

spec:
  selector:
    app: backend

  ports:
    - port: 8000
      targetPort: 8000
